version: '3.8'

services:
  lead-scoring-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - WORKERS=4
      - MODEL_PATH=/app/models/lead_scoring_model.pkl
    volumes:
      - ./models:/app/models:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped